### ISSUE TITLE
ایجاد گزارش گرمایشی تردد

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#411]
# Description

برای نمایش تردد ماشین‌ها در جاده‌ها به صورت رنگی در نقشه، می‌توانید از یک سیستم کدگذاری رنگی استفاده کنید. به عنوان مثال، جاده‌هایی با تردد بالا را با رنگ قرمز، تردد متوسط با رنگ نارنجی و تردد کم با رنگ زرد نشان دهید. کاربران می‌توانند ناحیه‌ای خاص را برای گزارش‌گیری انتخاب کنند یا گزارش کل کشور را مشاهده کنند. این گزارش‌ها می‌توانند بر اساس پردازش شبانه تهیه شوند و نیازی به به‌روزرسانی لحظه‌ای (real-time) ندارند. این روش به کاربران کمک می‌کند تا به راحتی وضعیت ترافیک را در مناطق مختلف مشاهده کنند.

# Acceptance Criteria

گزارش باید بر اساس ناحیه یا کل کشور باشد.
تلورانس مسیریابی به ازای هر نقطه، 150 متر است.
نیازی به پردازش real-time نیست.

# Tasks List

- [x] Moshaveran-IoT/GsTechCoreV1-GitLab#412
- [x] Moshaveran-IoT/GsTechCoreV1-GitLab#413
- [x] Moshaveran-IoT/Maintenance-Worker-Service#30
- [x] Moshaveran-IoT/GsTechCoreV1-GitLab#416
- [x] Moshaveran-IoT/GsTechCoreV1-GitLab#415

**Comment by mirmostafa** [comment]
در جلسه با آقای بشیری:
1- تلورانس مسیریابی به ازای هر نقطه از ۱۵۰ به ۵۰ متر تغییر کند.
2- سرعت‌های زیر ۵ کیلومتر بر ساعت نادیده گرفته شود.

**Comment by Maedehoseyni** [comment]
getColor(count) {
        if (count <= 2) {
            return '#0071a2'; // blue
        } else if (count > 2 && count <= 5) {
            return '#24b045'; // green
        } else if (count > 5 && count <= 10) {
            return '#eedb05'; // yellow
        } else if (count > 10 && count <= 15) {
            return '#ee6a05'; // orange
        } else {
            return '#d72222'; // red
        }
    }

**Comment by Maedehoseyni** [comment]
getColor(count) {
        if (count <= 2) {
            return '#0071a2'; // blue
        } else if (count > 2 && count <= 5) {
            return '#24b045'; // green
        } else if (count > 5 && count <= 10) {
            return '#eedb05'; // yellow
        } else if (count > 10 && count <= 15) {
            return '#ee6a05'; // orange
        } else {
            return '#d72222'; // red
        }
    }
