### ISSUE TITLE
تعریف سطوح دسترسی به اشخاص

### ISSUE THREAD

**Issue by Akavoosi** [Moshaveran-IoT/GsTechCoreV1-GitLab#439]
### Description

دسترسی به سطوح مختلف اشخاص برای هر ماژول ایجاد گردد. 
مثلا مدیر تعمیرات صفحه مانیتورینگ را نبیند.

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] #443

**Comment by Maedehoseyni** [comment]
- [ ] ایجاد گروه کاربری در فرانت و درست کردن عملیات های دیتایی
- [ ] ایجاد معرفی کاربری در فرانت
- [ ] و درست کردن عملیات های دیتایی درست کردن پاپ آپ permissiones

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] #444 
- [ ] #445

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] #446

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] #448

**Comment by mirmostafa** [comment]
# Tasks List

- [ ] #449

**Comment by mirmostafa** [comment]
## Tasks List

- [ ] تست کامل User Story توسط UI

**Comment by mirmostafa** [comment]
## Tasks List

- [ ] تبدیل منوی درختی به منوی فلت در `systemMenu`

**Comment by mirmostafa** [comment]
## Tasks List

- [ ] #456

**Comment by mirmostafa** [comment]
مشکل کجاست؟ @Akavoosi

**Comment by Akavoosi** [comment]
حل شد
