### ISSUE TITLE
باگ‌های ریز Maintenance

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#440]
### Description

به مرور زمان، چند ریسک در Maintenance Service دیده شده:
# Tasks List

- [ ] در فواصل زمانی کم، برنامه، سرعت را اشتباه محاسبه مبکند
- [ ] در فواصل زمانی زیاد، برنامه، سرعت را اشتباه محاسبه مبکند
- [ ] محاسبه باز در مرز ایران. باید محدودتر شود
- [ ] انتخاب اشتباه داده‌ها بر اساس تاریخ
