### ISSUE TITLE
ایجاد APIی اجرای کوئری‌های داشبورد

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#487]
### Description

در داشبورد موجود، چندین ویجت قرار دارند که هر کدام با استفاده از یک شناسه (ID) به کوئری‌های مختلفی که در پایگاه داده ذخیره شده‌اند، متصل می‌شوند.
در حال حاضر، نتیجه اجرای هر کوئری به صورت تعداد کل رکوردها در ویجت به نمایش درمی‌آید.
لازم است تا یک API طراحی و پیاده‌سازی شود که با دریافت ID، کوئری مربوطه را اجرا نماید.

### Acceptance Criteria

ورودی API شامل یک شناسه (ID) به همراه گزینه‌های بارگذاری (Load Options) است. فرمت خروجی API دینامیک بوده و بسته به نتایج کوئری تعیین می‌گردد. خروجی API متناسب با پارامترهای گزینه‌های بارگذاری، شامل صفحه‌بندی، مرتب‌سازی و گروه‌بندی خواهد بود.

### Tasks List

- [ ] توسعه کنترلر مدیریت dashboard
- [ ] ایجاد API اجرای کوئری ویجت
- [ ] ایجاد مدل dynamic بر اساس خروجی کوئری
- [ ] اعمال LoadOption به خروجی API

**Comment by mirmostafa** [comment]
## Tasks List

- [ ] #491

**Comment by mirmostafa** [comment]
# ☢ نیازمندی‌ها

- فیلد `CustomerAssignmentId` حتما در کوئری باشد.
- در صورت وجود nested query، کوئری داخلی، حاوی ORDER BY داخلی نباشد.

**Comment by mirmostafa** [comment]
# ☢ نیازمندی‌ها

- اگر به داده‌های روز جاری نیاز هست، باید
    - یک فیلد با نام unique برای دریافت تاریخ امروز در نتیجه کوئری گنجانده شود
    - در API، عبارت `date=now` در query string قرار داده شود.

**Comment by mirmostafa** [comment]
## Tasks List

- [ ] #504

**Comment by Akavoosi** [comment]
@Maedehoseyni 
لطفا موارد چک و در صورت تایید DONE شود
