### ISSUE TITLE
سیستم امتیازدهی بر اساس تخلف تجاوز از سرعت غیرمجاز

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#538]
### Description

مرجع: #523 

### Tasks List

- [ ] ایجاد جدول امتیازدهی
- [ ] پیاده‌سازی امتیاز منقی لحظه‌ای

**Comment by mirmostafa** [comment]
## Tasks List

- [ ] ایجاد Trigger ثبت تخلف لحظه‌ای
- [ ] ایجاد SP محاسبه و ثبت امتیازات منفی
هنوز شرط ماکزیمم امتیاز منفی در بازه زمان، تحلیل و پیاده‌سازی نشده

**Comment by mirmostafa** [comment]
در حال تست نتیجه هستیم....

**Comment by mirmostafa** [comment]
تست، انجام شده. باید وارد مراحل بعدی شویم.

**Comment by Akavoosi** [comment]
بشووووویییید..........
