### ISSUE TITLE
پشتیبانی از Versioning

### ISSUE THREAD

**Issue by mirmostafa** [Moshaveran-IoT/GsTechCoreV1-GitLab#566]
### Description

روند کار بر اساس صحبتهای در حال انجام در [استراتژی نسخه‌بندی و یادداشت‌های انتشار](https://github.com/orgs/Moshaveran-IoT/discussions/2)، پیش برود

### User Stories List

- [ ] نهایی‌سازی تحلیل Versioning
- [ ] پیاده‌سازی database برای Versioning
- [ ] پیاده‌سازی backend برای Versioning
- [ ] پیاده‌سازی frontend برای Versioning

**Comment by mirmostafa** [comment]
بخش back-end تمام شده. منتظر بخش front هستم.

**Comment by mirmostafa** [comment]
طبق توافق با @Moshaveran-IoT/teams-leads ، نسخه simplify شد.
### Tasks List

- [ ] اعمال تغییرات در Discussion نسخه برنامه
- [ ] #587

**Comment by Maedehoseyni** [comment]
- [ ] اضافه شدن ورژن به صفحه اصلی 
- [ ] با کلیک تغییرات ورژن نمایش دهد

**Comment by Akavoosi** [comment]
مطابق توضیحات اعلامی در #584 بررسی مجدد گردد

**Comment by Maedehoseyni** [comment]
ورژن بر اساس نوع تغییرات کاملا اشتباه است اولا تعیین نوع بسیار دشوار است و اگر تعداد یک نوع خطا به 20 تا برسه چی عدد 4 رقمی میشه کاملا اشتباهه این مورد از لحاظ فنی رد است .

**Comment by Akavoosi** [comment]
@mirmostafa 
@Maedehoseyni 
مطابق جمعبندی جلسه اسپرینت اصلاح شود
